JECT-Study/Chzz-Market-Backend

build.gradle
src/main/resources/application-test.yml
src/main/resources/db/migration/V1__init.sql

[CHZZ-98] #done
- flyway 세팅을 하였습니다.
- 초기 V1 스크립트 파일을 추가하였습니다.
- 네이밍은 아래 공식문서 참고하시면 됩니다.
[공식문서](https://documentation.red-gate.com/fd/migrations-184127470.html#naming-1)
- 로컬에서는 yml 파일에 해당 부분을 추가하시면 됩니다
```
spring:
flyway:
enabled: true
baseline-on-migrate: true
``` 
[CHZZ-98]: https://chzz-market.atlassian.net/browse/CHZZ-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: flyway setting

---

.github/workflows/pr-title-and-branch-validation.yml
Dockerfile
src/main/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandler.java
src/test/java/org/chzz/market/domain/user/oauth2/CustomSuccessHandlerTest.java

[CHZZ-101]
- release/0.1.0 -> dev merge
[CHZZ-101]: https://chzz-market.atlassian.net/browse/CHZZ-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge release/0.1.0 into develop

---

.github/workflows/release-tag.yml
compose-local.yaml
nginx.conf
src/main/resources/db/migration/V1__init.sql

[CHZZ-110]
- nginx 업로드 용량 제한을 50MB로 설정하였습니다.
- git tag 생성부분을 삭제하고 릴리즈노트에서 생성한것으로 사용합니다
[CHZZ-110]: https://chzz-market.atlassian.net/browse/CHZZ-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: nginx 업로드 용량 제한 설정

---

.github/workflows/pr-title-and-branch-validation.yml
src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryImpl.java
src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
src/main/java/org/chzz/market/domain/product/controller/ProductController.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryImpl.java
src/main/java/org/chzz/market/domain/product/service/ProductService.java

[CHZZ-113]
- 경매/사전등록 상품 조회를 인증 기반으로 조회 가능한 엔드포인트 제공
- 기존 API와 유사하기에 별도 테스트는 처리하지 않았습니다
[CHZZ-113]: https://chzz-market.atlassian.net/browse/CHZZ-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: find registered product auction

---

src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/image/service/ImageService.java

[CHZZ-116]
- 이미지 CDN 경로 수정 ("/" 추가)
- S3 객체 키 추출 로직 수정으로 정확한 이미지 삭제 구현
- 파일 타입 식별을 위한 확장자 추가
- 경매 상세 조회 파라미터명 수정 viewType -> type
[CHZZ-116]: https://chzz-market.atlassian.net/browse/CHZZ-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 이미지 CDN 경로 수정

---

.github/workflows/pr-title-and-branch-validation.yml
src/main/java/org/chzz/market/domain/bid/entity/Bid.java
src/main/resources/db/migration/V2__update_default_count_value.sql
src/main/resources/db/migration/V3__reorder_columns.sql
src/test/java/org/chzz/market/domain/bid/service/BidServiceTest.java

[CHZZ-115]
- 입찰 가능 횟수 3에서 2로 변경하였습니다.
- flyway  파일 두개 추가하였습니다.
1. 3에서 2로 변경 쿼리
2. 가독성을 위해 컬럼 순서 변경 쿼리
- jira bot 이 PR 수정시 PR 검사 auction skip 추가
[CHZZ-115]: https://chzz-market.atlassian.net/browse/CHZZ-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 입찰 가능 횟수 변경

---

src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java

[CHZZ-122]
- 상품 상세 정보 조회시 `category`도 조회되도록 수정
- ![image](https://github.com/user-attachments/assets/ad1d1632-5833-4470-bf62-6a8e5d06112e)
[CHZZ-122]: https://chzz-market.atlassian.net/browse/CHZZ-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: fix register request

---

src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java

[CHZZ-124]
- 내가 등록한 사전 경매 제품 조회 쿼리 수정
[CHZZ-124]: https://chzz-market.atlassian.net/browse/CHZZ-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 내가 등록한 사전 경매 제품 조회 쿼리 수정

---

nginx.conf
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/user/entity/User.java
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java

[CHZZ-126], [CHZZ-130]
- nginx 포트 매핑 수정
- auction history 조건 추가
- 불필요한 entity 양방향 매핑 제거
- ![image](https://github.com/user-attachments/assets/37986f79-2954-4bfc-9968-541d7686bd95)
[CHZZ-126]: https://chzz-market.atlassian.net/browse/CHZZ-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHZZ-130]: https://chzz-market.atlassian.net/browse/CHZZ-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: fix auction history condition

---

.github/workflows/pr-title-and-branch-validation.yml
.github/workflows/pr_review_reminder.yml

[CHZZ-133]
- 리뷰 리마인더가 모두가 리뷰할게 없으면 알림을 보내지 않도록 설정하였습니다.
- PR 유효성 검사가 jira[bot]이 수정할때는 스킵하도록 설정하였습니다.
[CHZZ-133]: https://chzz-market.atlassian.net/browse/CHZZ-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: github action skip 상황 추가

---

src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
src/main/java/org/chzz/market/domain/image/entity/Image.java
src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
src/main/java/org/chzz/market/domain/image/repository/ImageRepository.java
src/main/java/org/chzz/market/domain/image/service/ImageService.java
src/main/java/org/chzz/market/domain/product/controller/ProductController.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/service/ProductService.java
src/main/resources/db/migration/V5__add_image_sequence.sql
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-134]
- 이미지 업로드 방식 변경
- 삭제되지 않을(순서 변경은 허용) 이미지들의 순서를 요청받음
- 새로 생긴 이미지들의 
- ![image](https://github.com/user-attachments/assets/dbeacaea-33b1-4116-b5cb-bdd6e6d486bf)
- 테스트코드 일부를 변경사항에 따라 반영하는 과정에서 행위검증 테스트로 최대한 변경했습니다. 나름 점검해봐야하는 메서드들만 검증하도록 처리해봤으나 추가로 검증이 필요한 부분이 있다면 리뷰 남겨주세요. 추가로 기존 테스트코드중 일부 테스트코드만 변경하였으니 기존 테스트코드중에도 검증해봐야할 부분이 있다면 리뷰 남겨주세요.
[CHZZ-134]: https://chzz-market.atlassian.net/browse/CHZZ-134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: fix image upload method

---

src/main/java/org/chzz/market/domain/auction/type/TestService.java

[CHZZ-139]
- 테스트 경매 API 시 이미지 시퀀스 로직 누락 수정했습니다.
[CHZZ-139]: https://chzz-market.atlassian.net/browse/CHZZ-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 테스트 API 이미지 저장 로직 시퀀스 누락 수정

---

.github/release-drafter-config.yml
.github/workflows/pr-title-and-branch-validation.yml
.github/workflows/pr_review_reminder.yml
README.md
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
src/main/java/org/chzz/market/domain/auction/type/TestService.java
src/main/java/org/chzz/market/domain/image/entity/Image.java
src/main/java/org/chzz/market/domain/image/error/ImageErrorCode.java
src/main/java/org/chzz/market/domain/image/repository/ImageRepository.java
src/main/java/org/chzz/market/domain/image/service/ImageService.java
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/main/java/org/chzz/market/domain/product/controller/ProductController.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustom.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/service/ProductService.java
src/main/java/org/chzz/market/domain/user/oauth2/CustomFailureHandler.java
src/main/resources/db/migration/V5__add_image_sequence.sql
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-141]
- release: 0.2.1
[CHZZ-141]: https://chzz-market.atlassian.net/browse/CHZZ-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release: 0.2.1

---

src/main/java/org/chzz/market/domain/address/exception/AddressErrorCode.java
src/main/java/org/chzz/market/domain/address/exception/AddressException.java
src/main/java/org/chzz/market/domain/order/entity/Order.java
src/main/java/org/chzz/market/domain/order/repository/OrderRepository.java
src/main/java/org/chzz/market/domain/order/service/OrderService.java
src/main/java/org/chzz/market/domain/payment/dto/DeliveryRequest.java
src/main/java/org/chzz/market/domain/payment/dto/SuccessfulPaymentEvent.java
src/main/java/org/chzz/market/domain/payment/dto/request/ApprovalRequest.java
src/main/java/org/chzz/market/domain/payment/error/PaymentErrorCode.java
src/main/java/org/chzz/market/domain/payment/repository/PaymentRepository.java
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/main/resources/db/migration/V7__add_orders_table.sql

[CHZZ-162]
- 결제 기록을 확인해 결제된 이력이 있는경우 예외처리
- 결제 성공시 이벤트 처리를 통해 주문정보 작성
[CHZZ-162]: https://chzz-market.atlassian.net/browse/CHZZ-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 결제 점검 및 주문 도메인 추가

---

.github/workflows/deployment-config.yml

[CHZZ-168]
- github action CD 버그를 수정하였습니다.
[CHZZ-168]: https://chzz-market.atlassian.net/browse/CHZZ-168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: CD github action 버그 수정

---

src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java

[CHZZ-170]
- 상품 수정 요청 필드 검증 조건 수정
[CHZZ-170]: https://chzz-market.atlassian.net/browse/CHZZ-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 상품 수정 요청 필드 수정

---

src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
src/main/java/org/chzz/market/domain/address/controller/AddressApi.java
src/main/java/org/chzz/market/domain/address/dto/DeliveryRequest.java
src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
src/main/java/org/chzz/market/domain/bid/controller/BidApi.java
src/main/java/org/chzz/market/domain/order/service/OrderService.java
src/main/java/org/chzz/market/domain/payment/controller/PaymentApi.java
src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
src/main/java/org/chzz/market/domain/product/controller/ProductApi.java
src/main/java/org/chzz/market/domain/user/controller/UserApi.java
src/main/java/org/chzz/market/domain/user/controller/UserController.java

[CHZZ-172]
- 전화번호 정규식 수정하였습니다.
- 닉네임 중복검사 유효성 추가하였습니다.
- 누락된 OrderService 트랙잭션 추가하였습니다.
[CHZZ-172]: https://chzz-market.atlassian.net/browse/CHZZ-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 일부 API 유효성 검사 수정

---

src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/main/java/org/chzz/market/domain/user/dto/request/UpdateUserProfileRequest.java
src/main/java/org/chzz/market/domain/user/dto/request/UserCreateRequest.java
src/test/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequestTest.java

[CHZZ-177]
- 경매 등록 및 수정시 상품 설명에 줄바꿈을 허용하였습니다.
- 회원가입 및 수정시 자기소개에 줄바꿈을 허용하였습니다.
[CHZZ-177]: https://chzz-market.atlassian.net/browse/CHZZ-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 일부 필드 요청시 줄바꿈 허용으로 수정

---

src/main/java/org/chzz/market/common/config/SecurityConfig.java
src/main/java/org/chzz/market/common/config/SpringDocConfig.java
src/main/java/org/chzz/market/common/config/WebConfig.java
src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailApi.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailController.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
src/main/java/org/chzz/market/domain/auctionv2/dto/view/AuctionType.java
src/main/java/org/chzz/market/domain/auctionv2/dto/view/UserAuctionType.java
src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2Repository.java
src/main/java/org/chzz/market/domain/bid/controller/BidController.java
src/main/java/org/chzz/market/domain/delivery/controller/DeliveryController.java
src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
src/main/java/org/chzz/market/domain/payment/controller/PaymentController.java
src/main/java/org/chzz/market/domain/product/controller/ProductController.java
src/main/java/org/chzz/market/domain/user/controller/UserController.java
src/main/resources/db/migration/V14__create_v2_auction.sql

[CHZZ-180]
- V2 경매 API에 쓰일 경매 Entity 와 API 뼈대 기반을 만들었습니다.
[CHZZ-180]: https://chzz-market.atlassian.net/browse/CHZZ-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 경매 V2 API 구조 생성

---

src/main/java/org/chzz/market/common/config/AWSConfig.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailApi.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailController.java
src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionStatus.java
src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
src/main/java/org/chzz/market/domain/auctionv2/entity/Category.java
src/main/java/org/chzz/market/domain/auctionv2/error/AuctionErrorCode.java
src/main/java/org/chzz/market/domain/auctionv2/error/AuctionException.java
src/main/java/org/chzz/market/domain/auctionv2/service/AuctionDeleteService.java
src/main/java/org/chzz/market/domain/imagev2/entity/ImageV2.java
src/main/java/org/chzz/market/domain/imagev2/error/ImageErrorCode.java
src/main/java/org/chzz/market/domain/imagev2/error/exception/ImageException.java
src/main/java/org/chzz/market/domain/imagev2/service/ImageDeleteService.java
src/main/java/org/chzz/market/domain/likev2/entity/LikeV2.java
src/main/java/org/chzz/market/domain/likev2/repository/LikeV2Repository.java
src/main/resources/db/migration/V15__create_like_image.sql
src/test/java/org/chzz/market/domain/auctionv2/service/AuctionDeleteServiceTest.java
src/test/java/org/chzz/market/domain/imagev2/service/ImageDeleteServiceTest.java

[CHZZ-181]
- 경매 삭제 API를 전환하였습니다.
> - [ ] 정식 경매 목록 조회
> - [ ] 사전 경매 목록 조회
> - [ ] 정식 경매 베스트 조회
> - [ ] 정식 경매 마감임박 조회
> - [ ] 경매 카테고리 조회
> - [ ] 내가 등록한 진행 중인 경매 목록 조회
> - [ ] 내가 등록한 종료된 경매 목록 조회
> - [ ] 내가 등록한 사전 경매 목록 조회
> - [ ] 내가 성공(낙찰)한 경매 목록 조회
> - [ ] 내가 실패한(낙찰 실패) 경매 목록 조회
> - [ ] 내가 좋아요(찜)한 경매 목록 조회
> - [ ] 경매 등록
> - [ ] 테스트 경매 추가
> - [ ] 경매 상세 조회
> - [ ] 경매 입찰 목록 조회
> - [ ] 경매 낙찰 정보 조회
> - [ ] 사전 경매에서 정식 경매로 전환
> - [ ] (사전) 경매 좋아요(찜) 요청 및 취소
> - [ ] (사전) 경매 수정
> - [ ] (사전) 경매 취소
> 
- 서비스 함수 테스트 코드 작성방법이 맞는지 확인해주세요.
[CHZZ-181]: https://chzz-market.atlassian.net/browse/CHZZ-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 경매 삭제 API 전환

---

src/main/java/org/chzz/market/common/config/SecurityConfig.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/BaseAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/OfficialAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/PreAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/dto/view/AuctionType.java
src/main/java/org/chzz/market/domain/auctionv2/dto/view/UserAuctionType.java
src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepository.java
src/main/java/org/chzz/market/domain/auctionv2/service/AuctionLookupService.java
src/test/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepositoryTest.java

refactor: 경매 목록 조회 API 전환

---

src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Api.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionV2Controller.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/EndedAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/LostAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/ProceedingAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/dto/response/WonAuctionResponse.java
src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepository.java
src/main/java/org/chzz/market/domain/auctionv2/service/AuctionMyService.java
src/test/java/org/chzz/market/domain/auctionv2/repository/AuctionV2QueryRepositoryTest.java

refactor: 사용자의 경매 조회 API 전환

---

src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionQueryRepository.java

fix: 누락된 좋아요순 정렬 추가

---

src/main/java/org/chzz/market/domain/auction/dto/request/UpdateAuctionRequest.java

fix: 경매 수정 시 설명 필드 정규식 오타 수정

---

src/main/java/org/chzz/market/domain/auction/schedule/AuctionEndJob.java

fix: 경매 종료 스케줄링 의존성 주입 문제 수정

---

src/main/java/org/chzz/market/domain/oauth2/service/CustomFailureHandler.java
src/main/java/org/chzz/market/domain/oauth2/service/CustomSuccessHandler.java

[CHZZ-이슈번호]
- 로그인 및 로그아웃 url 변경

refactor: 로그인 및 로그아웃 url 변경
