JECT-Study/Chzz-Market-Backend

.github/workflows/pr-title-and-branch-validation.yml
src/main/java/org/chzz/market/common/config/RedisConfig.java
src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/type/TestService.java
src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
src/main/resources/application-test.yml
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java

[CHZZ-118]
- 로그인 한 상태에서 입찰 이력이 없을 때 입찰 가능 횟수가 0으로 표시되는 문제를 수정하였습니다.
- 이를 입찰 한적이 없거나 비로그인 유저인 경우 0이 아닌 3으로 수정하였습니다.
- 경매종료 임시테스트 api를 기존 파일에 최대한 영향없게 새롭게 클래스하나 만들었으니 추후에 삭제하면 될것같습니다
[CHZZ-118]: https://chzz-market.atlassian.net/browse/CHZZ-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 입찰 이력이 없을 때 입찰 가능 횟수가 0으로 표시되는 문제 수정

---

src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepository.java
src/main/java/org/chzz/market/domain/product/service/ProductService.java
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-119]
* 내가 실패한 경매 조회 API의 입찰 최고가를 올바른 서브쿼리로 값이 출력되도록 개선하였습니다.
[CHZZ-119]: https://chzz-market.atlassian.net/browse/CHZZ-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 내가 실패한 경매 조회에서 입찰 최고가 수정

---

src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-122]
- 사전등록 수정요청 DTO 이름 필드 수정 (name -> productName)
- 경매 상세정보 조회에 카테고리 필드 추가
[CHZZ-122]: https://chzz-market.atlassian.net/browse/CHZZ-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 사전등록 수정 요청 DTO 일부 필드 이름 수정

---

src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/dto/ProductDetailsResponse.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/user/dto/response/UserProfileResponse.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-125]
- Release 0.1.2
[CHZZ-125]: https://chzz-market.atlassian.net/browse/CHZZ-125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

release: 0.1.3

---

.github/workflows/pr_review_reminder.yml

[CHZZ-129]
- github action으로 리뷰 리마인더를 action으로 있으면 좋을 것 같아 추가해봤습니다.
- 일단 12시, 18시 두번 알림 가게 해뒀습니다
[CHZZ-129]: https://chzz-market.atlassian.net/browse/CHZZ-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Pull Request review reminder action 추가

---

.github/release-drafter-config.yml
src/main/java/org/chzz/market/domain/auction/service/register/AuctionRegisterService.java
src/main/java/org/chzz/market/domain/auction/service/register/PreRegisterService.java
src/main/java/org/chzz/market/domain/image/entity/Image.java
src/main/java/org/chzz/market/domain/image/repository/ImageRepository.java
src/main/java/org/chzz/market/domain/image/service/ImageService.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/main/java/org/chzz/market/domain/product/service/ProductService.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-137]
- 이미지 등록 및 삭제시 연관관계 메서드 사용으로 변경하였습니다.
- 상품 수정시 RequestParam에 dto 가 포함되서 해당 dto는 map에서 삭제하도록 했습니다.
- Product, Image 각각 도메인 메서드를 활용하였습니다.
- Product에 이미지 리스트에 `CascadeType.PERSIST`,`orphanRemoval = true` 추가하였습니다.
[CHZZ-137]: https://chzz-market.atlassian.net/browse/CHZZ-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 상품 수정시 이미지 등록 버그 수정

---

.github/workflows/pr-title-and-branch-validation.yml
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/main/java/org/chzz/market/domain/product/error/ProductErrorCode.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/service/ProductService.java
src/main/java/org/chzz/market/domain/user/oauth2/CustomFailureHandler.java
src/test/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/product/service/ProductServiceTest.java

[CHZZ-140]
- 정식 경매 제품의 productId로 사전 경매 조회시 조회되는 버그를 수정하였습니다.
- 서비스에서 한번 검증하여 에러를 던졌습니다.
- 쿼리 단에서 조건 추가하였습니다.
[CHZZ-140]: https://chzz-market.atlassian.net/browse/CHZZ-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 정식 경매 제품을 사전 경매 조회 시 조회되는 버그 수정

---

.github/workflows/deployment-config.yml
.github/workflows/intergration-config.yml
src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
src/main/java/org/chzz/market/domain/auction/dto/response/UserEndedAuctionResponse.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java

[CHZZ-143]
- 종료된 내가 등록한 경매 API 추가했습니다.
- 진행중인 내가 등록한 경매 API 추가했습니다.
- 하나의 API로 처리하려다가 첫번째 API는 낙찰유무, 결제유무, 낙찰금액 의 필드가 추가되서 복잡성을 고려하여 분리하였습니다.
- 내가 등록한 종료된 경매 쿼리에서 결제 상태가 DONE으로 하는게 맞는지 확인해주세요 @YeaChan05 
[CHZZ-143]: https://chzz-market.atlassian.net/browse/CHZZ-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 내가 등록한 경매 상태값에 따라 API 분리

---

src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/entity/Product.java
src/main/resources/application-test.yml
src/main/resources/db/migration/V6__add_index_on_product.sql
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java

[CHZZ-155]
- 인기순 정렬 조건에서 취소된 입찰 제외하여 정렬되도록 수정
- 적용되지 않던 product의 index 적용
- ![image](https://github.com/user-attachments/assets/c25eb2a9-e1c0-44c5-b4e5-7ff236d64a69)
- 테스트가 다소 부실한감이 있습니다
하지만 코드 실행시 정렬 조건을 보고 확신이 있어 pr 올립니다
```SQl
order by (select count(b4_0.bid_id) from bid b4_0 where b4_0.auction_id=a1_0.auction_id and b4_0.status=?)
```
[CHZZ-155]: https://chzz-market.atlassian.net/browse/CHZZ-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 인기순 정렬 조건 수정

---

.github/workflows/pr-title-and-branch-validation.yml
src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
src/main/java/org/chzz/market/domain/auction/dto/response/StartAuctionResponse.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
src/main/java/org/chzz/market/domain/auction/type/TestService.java
src/main/java/org/chzz/market/domain/bid/controller/BidController.java
src/main/java/org/chzz/market/domain/bid/dto/query/BiddingRecord.java
src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustom.java
src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/bid/service/BidService.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/main/resources/db/migration/V6__add_index_on_product.sql
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java
src/test/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImplTest.java

[CHZZ-144]
- /auctions/history 와 /bids API가 중복된 API여서 auctions/history를 삭제하였습니다.
- bids API에 동적쿼리를 적용하여 현재는 진행중인 입찰목록 조회 API만을 필요로 하지만, 확장성을 위해 동적쿼리로 수정하였습니다.
- 파라미터가 안들어오면 전체 목록조회입니다.
[CHZZ-144]: https://chzz-market.atlassian.net/browse/CHZZ-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 나의 입찰 목록 조회 API 동적쿼리로 수정

---

src/main/java/org/chzz/market/common/config/SecurityConfig.java
src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
src/main/java/org/chzz/market/common/error/handler/GlobalExceptionHandler.java
src/main/java/org/chzz/market/domain/notification/controller/NotificationController.java
src/main/java/org/chzz/market/domain/notification/service/NotificationService.java

[CHZZ-145]
- SSE 에러 콜백 메서드와 예외 핸들러를 변경해 에러로그 찍히는걸 처리하였습니다.
- 해당 연결을 완료처리 할 때 인증이 필요한 API여서 해당 API를 security에서 인증허용하고, 컨트롤러에서 인증 체크 하였습니다.
- SSE연결을 하고 클라이언트에서 브라우저를 끄거나 연결 끊을시
- SSE 타임아웃 시 (해당 연결 정리 후 클라이언트에서 재연결 요청 후 재연결)
[CHZZ-145]: https://chzz-market.atlassian.net/browse/CHZZ-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: SSE 에러처리 버그 수정

---

nginx.conf
src/main/java/org/chzz/market/common/config/SchedulingConfig.java
src/main/java/org/chzz/market/domain/notification/repository/EmitterRepository.java
src/main/java/org/chzz/market/domain/notification/repository/EmitterRepositoryImpl.java
src/main/java/org/chzz/market/domain/notification/service/NotificationService.java

[CHZZ-156]
- 서버 성능을 위해 기존에 끊긴 SSE 연결 정리를 위해 주기적으로 저장된 SseEmitter에 하트비트 인 빈 주석을 보냈습니다.
- 주기적으로 확인하기 때문에 잦은 재연결 요청을 받지 않기 위해 타임아웃 시간을 길게 잡았습니다.
- 현재 경매시간이 24시간이기 때문에, 경매 시작하자마자 켜뒀다고 가정하에 볼 수 있게 알림이 올 수 있게 하기 위해 25시간으로 설정 해뒀습니다.
- Nginx의 proxy_read_timeout도 서버에서 하트비트를 1분마다 보내기 때문에 1분보다 살짝 긴 1분 30초안에 응답이 없으면 연결을 끊습니다.
- 간단한 스케줄링이기 때문에 기본 스프링 스케줄러 사용하였습니다.(Quartz는 복잡한 스케줄러나 특정시각에 예약스케줄러에 사용)
- 여기에 내용을 입력하세요.
[CHZZ-156]: https://chzz-market.atlassian.net/browse/CHZZ-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: SSE heartbeat 기능 추가

---

src/main/java/org/chzz/market/domain/auction/controller/AuctionController.java
src/main/java/org/chzz/market/domain/auction/dto/response/LostAuctionResponse.java
src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionDetailsResponse.java
src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionResponse.java
src/main/java/org/chzz/market/domain/auction/entity/Auction.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustom.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
src/main/java/org/chzz/market/domain/bid/repository/BidRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java

[CHZZ-157]
- 낙찰자가 낙찰정보를 조회하는 API를 추가하였습니다.
- 성공한 경매목록 조회 API에서 응답하는 DTO를 사용하였습니다.
- 낙찰자가 아닐시 403 에러를 반환합니다.
- 이미 서비스 단에서 낙찰자가 있는 경우에만 쿼리가 실행되도록 처리했지만, fetchOne이 null을 반환하면 NullPointerException이 발생할 위험이 있기에 이를 방지하기 위해 Optional로 처리하여, 값이 없는 경우에는 global exception 404 에러를 던지도록 했습니다.
- 기존에 상품과 이미지를 조인해서 대표이미지 가져오는 부분에서 불필요한 부분을 제거해 최적화하였습니다.
[CHZZ-157]: https://chzz-market.atlassian.net/browse/CHZZ-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 낙찰 정보 조회 기능 추가

---

src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
src/main/java/org/chzz/market/domain/auction/dto/response/UserEndedAuctionResponse.java
src/main/java/org/chzz/market/domain/auction/dto/response/WonAuctionResponse.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/order/service/OrderService.java
src/main/java/org/chzz/market/domain/payment/dto/DeliveryRequest.java
src/main/java/org/chzz/market/domain/payment/dto/ShippingAddressRequest.java
src/main/java/org/chzz/market/domain/payment/dto/SuccessfulPaymentEvent.java
src/main/java/org/chzz/market/domain/payment/dto/request/ApprovalRequest.java
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java

[CHZZ-163]
- 주문 여부 추가
- 주문을 했다면 주문Id 추가 (추후 주문 내역 조회에 사용)
- 결제여부 ⇒ 주문여부 변경
- ![image](https://github.com/user-attachments/assets/402bb2f5-19d7-4000-b2e3-17df7792291c)
[CHZZ-163]: https://chzz-market.atlassian.net/browse/CHZZ-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 주문 도입 이후 나의 성공한 경매 목록 조회 API 수정

---

src/main/java/org/chzz/market/domain/auction/controller/AuctionApi.java
src/main/java/org/chzz/market/domain/auction/dto/response/AuctionDetailsResponse.java
src/main/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImpl.java
src/main/java/org/chzz/market/domain/auction/service/AuctionService.java
src/main/java/org/chzz/market/domain/order/entity/Order.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/test/java/org/chzz/market/domain/auction/repository/AuctionRepositoryCustomImplTest.java
src/test/java/org/chzz/market/domain/auction/service/AuctionServiceTest.java

[CHZZ-164]
- 상세정보에서 주문 여부, 낙찰자 여부, 낙찰여부 필드 세개를 추가하였습니다.
- 주문 여부는 민감한 정보로 판단하여, 판매자와 낙찰자만 확인할 수 있도록 처리하였습니다.
- 판매자나 낙찰자가 아닐 경우, 주문 여부 필드를 `null`로 처리하였고, `@JsonInclude` 어노테이션을 통해 해당 필드는 응답에서 제외되었습니다.
- 쿼리에서 `Case When`을 사용해 처리할 수 있었으나, 해당 부분은 비즈니스 로직이므로 서비스 레이어에서 처리하는 것이 적절하다고 판단하였습니다. 
- 꼼꼼하게 리뷰 부탁드립니다!
[CHZZ-164]: https://chzz-market.atlassian.net/browse/CHZZ-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 상세정보 조회 API에 주문 및 낙찰 여부 추가

---

src/main/java/org/chzz/market/domain/payment/entity/Payment.java
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/test/java/org/chzz/market/domain/payment/service/PaymentServiceTest.java

[CHZZ-166]
- 결제 승인시 점검 조건을 `DONE` 상태의 결제가 있는경우가 아닌 없는경우로 변경
- ![image](https://github.com/user-attachments/assets/99802fb7-5fab-4791-9306-bb0ab03b74a4)
[CHZZ-166]: https://chzz-market.atlassian.net/browse/CHZZ-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: 결제 승인 점검 로직 수정

---

.github/workflows/deployment-config.yml
.github/workflows/intergration-config.yml
build.gradle
src/main/java/org/chzz/market/common/aop/redisrock/AopForTransaction.java
src/main/java/org/chzz/market/common/aop/redisrock/CustomSpringELParser.java
src/main/java/org/chzz/market/common/aop/redisrock/DistributedLock.java
src/main/java/org/chzz/market/common/aop/redisrock/DistributedLockAop.java
src/main/java/org/chzz/market/common/config/AWSConfig.java
src/main/java/org/chzz/market/common/config/RedisConfig.java
src/main/java/org/chzz/market/common/config/RedissonConfig.java
src/main/java/org/chzz/market/common/dto/ApiEndpoint.java
src/main/java/org/chzz/market/common/error/GlobalErrorCode.java
src/main/java/org/chzz/market/common/filter/JWTFilter.java
src/main/java/org/chzz/market/common/util/CookieUtil.java
src/main/java/org/chzz/market/domain/notification/entity/NotificationType.java
src/main/java/org/chzz/market/domain/token/service/TokenService.java
src/main/java/org/chzz/market/domain/user/controller/UserController.java
src/main/resources/application-test.yml
src/test/java/org/chzz/market/MarketApplicationTests.java
src/test/java/org/chzz/market/common/AWSConfig.java
src/test/java/org/chzz/market/domain/token/service/TokenServiceTest.java

[CHZZ-175]
- 리프레쉬토큰으로 재발행 시 동시성 오류가 발생해서 분산락 적용으로 해결하였습니다.
- 같은 리프레쉬토큰으로 여러개의 재발행 요청이 오면 하나의 재발행만 성공 후 나머지는 예외가 던져지게 됩니다.
- 기존 기본적인 데이터 저장 및 Pub/Sub으로 Redis  Lettece를 사용했지만, 분산락은 Redisson 을 사용하였습니다.
- 분산 락의 간편한 구현, 복잡한 동시성 문제 해결에 특화 등의 장점인 이유입니다.
- 커스텀 어노테이션을 추가하였습니다.
아래의 링크를 참고하였습니다.
[풀필먼트 입고 서비스팀에서 분산락을 사용하는 방법 - Spring Redisson](https://helloworld.kurly.com/blog/distributed-redisson-lock/)
- 초기 홈 화면 호출
- 만료된 토큰으로 새로고침 (하나의 재발행만 성공)
- 이 부분은 프론트에서 하나의 재발행 요청으로 묶어 호출하는 것으로 해결하였지만, 이는 서버에서도 막아야된다고 생각해 처리하였습니다.
[CHZZ-175]: https://chzz-market.atlassian.net/browse/CHZZ-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: jwt 토큰 재발행시 동시성 문제 해결 및 분산락 적용

---

src/main/java/org/chzz/market/domain/auction/dto/request/BaseRegisterRequest.java
src/main/java/org/chzz/market/domain/bid/dto/BidCreateRequest.java
src/main/java/org/chzz/market/domain/order/service/OrderService.java
src/main/java/org/chzz/market/domain/payment/dto/SuccessfulPaymentEvent.java
src/main/java/org/chzz/market/domain/payment/dto/request/ApprovalRequest.java
src/main/java/org/chzz/market/domain/payment/dto/request/ShippingAddressRequest.java
src/main/java/org/chzz/market/domain/payment/service/PaymentService.java
src/main/java/org/chzz/market/domain/product/dto/UpdateProductRequest.java
src/test/java/org/chzz/market/domain/payment/service/PaymentServiceTest.java

[CHZZ-176]
- 입찰, 경매 등록 등 금액 입력이 가능한 요청들의 금액 범위를 토스 단일 최대 결제가능 금액 한도인 200만원으로 지정
[CHZZ-176]: https://chzz-market.atlassian.net/browse/CHZZ-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: 금액 범위 수정

---

src/main/java/org/chzz/market/domain/product/dto/ProductResponse.java
src/main/java/org/chzz/market/domain/product/repository/ProductRepositoryCustomImpl.java

[CHZZ-178]
- 사전 등록 상품 목록 조회 응답에 판매자임을 확인해주는 `isSeller` 필드 추가
[CHZZ-178]: https://chzz-market.atlassian.net/browse/CHZZ-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 사전 등록 상품 목록 조회에 isSeller 추가

---

.github/workflows/pr_review_reminder.yml
README.md
src/main/java/org/chzz/market/common/aop/redisrock/DistributedLockAop.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailApi.java
src/main/java/org/chzz/market/domain/auctionv2/controller/AuctionDetailController.java
src/main/java/org/chzz/market/domain/auctionv2/entity/AuctionV2.java
src/main/java/org/chzz/market/domain/auctionv2/error/AuctionErrorCode.java
src/main/java/org/chzz/market/domain/auctionv2/repository/AuctionV2Repository.java
src/main/java/org/chzz/market/domain/bid/controller/BidApi.java
src/main/java/org/chzz/market/domain/bid/controller/BidController.java
src/main/java/org/chzz/market/domain/bid/repository/BidQueryRepository.java
src/main/java/org/chzz/market/domain/bid/service/BidCancelLockService.java
src/main/java/org/chzz/market/domain/bid/service/BidCancelService.java
src/main/java/org/chzz/market/domain/bid/service/BidCreateService.java
src/main/java/org/chzz/market/domain/bid/service/BidLookupService.java
src/main/java/org/chzz/market/domain/bid/service/BidUpdateService.java
src/main/java/org/chzz/market/domain/likev2/repository/LikeV2Repository.java
src/main/java/org/chzz/market/domain/likev2/service/LikeUpdateService.java
src/test/java/org/chzz/market/domain/bid/service/BidCancelLockServiceTest.java
src/test/java/org/chzz/market/domain/bid/service/BidCreateServiceConcurrencyTest.java
src/test/java/org/chzz/market/domain/likev2/service/LikeUpdateServiceConcurrencyTest.java

[CHZZ-이슈번호]
- 일단 동시성 문제 원자적 연산으로 해결했습니다.

refactor: 입찰 API, 좋아요 API 전환

---

src/main/java/org/chzz/market/domain/image/service/ImageUploadService.java

[CHZZ-이슈번호]
- 경매 이미지 업로드시 각 이미지당 서로 다른 UUID를 prefix로 사용하도록 수정

refactor: 경매 이미지 업로드 prefix UUID 적용 방식 수정
